In [ ]:
# pip install pandas
import pandas as pd
# encoding="utf-8"로 읽으면 되는데 가끔 한글의 경우
# 오류가 날때가 있다 이때 cp949로 읽으면 된다.
df = pd.read_csv("아파트(매매)_실거래가_20261019190916_일산동구.csv",
            encoding="cp949",
            skiprows=15,
            thousands=","
            )
print(df)

In [ ]:
print(df.head(10))

In [ ]:
print(df.tail(10))

In [ ]:
print("전체 거래 건수",len(df))

In [ ]:
print("행과 열",df.shape)

In [11]:
print("컬럼 이름",df.columns)

컬럼 이름 Index(['NO', '시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일',
       '거래금액(만원)', '동', '층', '매수자', '매도자', '건축년도', '도로명', '해제사유발생일', '거래유형',
       '중개사소재지', '등기일자'],
      dtype='str')

In [ ]:
print("간략정보",df.info())

In [18]:
# result = df[["단지명","전용면적(㎡)","거래금액(만원)"]]
columns = ["단지명","전용면적(㎡)","거래금액(만원)"]
result = df[columns]
result = result.sort_values("거래금액(만원)",ascending=False)
print(result.head(10))

            단지명   전용면적(㎡)  거래금액(만원)
712   킨텍스원시티3블럭  120.8997    215000
148   킨텍스원시티2블럭  120.7152    200000
56    킨텍스원시티3블럭  104.9074    171000
1379  킨텍스원시티2블럭  104.9074    170000
746   킨텍스원시티2블럭  104.9074    170000
846   킨텍스원시티2블럭  104.9074    168000
1195  킨텍스원시티2블럭  104.9074    164000
1478  킨텍스원시티3블럭  104.9074    162500
722    일산요진와이시티  127.8600    157000
117    일산요진와이시티  127.8600    155000

In [ ]:
price = df["거래금액(만원)"]
# print(price)
condition = price >= 100000
result = df[condition]
# result = result[["단지명","전용면적(㎡)","거래금액(만원)"]]
# print(result.tail(10))
# 표 형태로 보기
display(result.tail(10))

In [36]:
result = df[df["단지명"].str.contains("킨텍스")]
# result = df[df["단지명"]=="킨텍스"]
# display(result[["단지명","거래금액(만원)"]])
result = result.sort_values(by="단지명")
result.to_excel("킨텍스_아파트.xlsx")

In [ ]:
result = df[df["전용면적(㎡)"].between(80,100)]
display(result[["단지명","전용면적(㎡)","거래금액(만원)"]])

In [ ]:
price = df["거래금액(만원)"]
print("평균 거래금액",price.mean())
print("최고가 거래금액",price.max())
print("최저 거래금액",price.min())

In [ ]:
result = (df.groupby("단지명")["거래금액(만원)"].mean().sort_values(ascending=False))
display(result)

### 문제 1. 1995년 이전에 건축된 아파트를 출력하세요.
### 문제 2. 거래금액이 5억 원 미만인 아파트 거래를 출력하세요.

In [56]:
year  = df["건축년도"]
condition = year < 1995
result = df[condition]
result = result[["단지명","거래금액(만원)","건축년도"]]
result = result.sort_values("건축년도",ascending=True)
result.to_excel("건축년도.xlsx",index=False)
display(result)

           단지명  거래금액(만원)  건축년도
1699      현대그린      8000  1989
1546      현대그린      7900  1989
1601      현대그린      6700  1989
1421      현대그린      7800  1989
1068      현대그린      7100  1989
...        ...       ...   ...
76    백송마을(두산)     40000  1994
1785  백송마을(대우)     42000  1994
1788  백마마을(쌍용)     47000  1994
8     호수마을(청구)     53000  1994
0     백마마을(쌍용)     44200  1994

[534 rows x 3 columns]

In [51]:
price  = df["거래금액(만원)"]
condition = price < 50000
print(df[condition])

        NO               시군구     번지    본번  부번         단지명  전용면적(㎡)    계약년월  \
0        1  경기도 고양시 일산동구 마두동    717   717   0    백마마을(쌍용)   70.430  202610
4        5   경기도 고양시 일산동구 풍동   1261  1261   0   숲속마을(7단지)   84.780  202610
7        8   경기도 고양시 일산동구 풍동  551-1   551   1        성원3차   84.980  202610
9       10  경기도 고양시 일산동구 백석동   1140  1140   0    백송마을(두산)   59.760  202610
10      11  경기도 고양시 일산동구 장항동    881   881   0    호수마을(현대)   70.140  202610
...    ...               ...    ...   ...  ..         ...      ...     ...
1785  1786  경기도 고양시 일산동구 백석동   1135  1135   0    백송마을(대우)   84.768  202601
1788  1789  경기도 고양시 일산동구 마두동    717   717   0    백마마을(쌍용)   70.430  202601
1791  1792  경기도 고양시 일산동구 중산동   1566  1566   0  중산마을10(동신)   84.900  202601
1792  1793  경기도 고양시 일산동구 중산동   1651  1651   0   산들마을2(대림)   84.940  202601
1796  1797  경기도 고양시 일산동구 백석동   1183  1183   0    백송마을(한신)   37.800  202601

      계약일  거래금액(만원)     동   층 매수자 매도자  건축년도          도로명 해제사유발생일  거래유형  \
0      15     44200     -  15  개인  개인  1994      경의로 333       -  중개거래
4      14     37700     -  18  개인  개인  2006   숲속마을1로 116       -  중개거래
7      12     33900     -  12  개인  개인  2000    고풍로 72-11       -  중개거래
9      12     31500     -   1  개인  개인  1994      강촌로 166       -  중개거래
10     11     47900     -  15  개인  개인  1994     노루목로 100       -  중개거래
...   ...       ...   ...  ..  ..  ..   ...          ...     ...   ...
1785    5     42000   601  11  개인  개인  1994      강촌로 192       -  중개거래
1788    4     47000   506  12  개인  법인  1994      경의로 333       -  중개거래
1791    3     33000  1001   9  개인  개인  1995      탄중로 430       -  중개거래
1792    3     43000   207   6  개인  개인  2002  고봉로278번길 17       -  중개거래
1796    2     23000   305  12  개인  개인  1992      백석로 109       -  중개거래

           중개사소재지      등기일자
0     경기 고양시 일산동구         -
4     경기 고양시 일산동구         -
7     경기 고양시 일산동구         -
9     경기 고양시 일산동구         -
10    경기 고양시 일산동구         -
...           ...       ...
1785  경기 고양시 일산동구  26.03.03
1788  경기 고양시 일산동구  26.03.27
1791  경기 고양시 일산동구  26.01.21
1792  경기 고양시 일산동구  26.02.10
1796  경기 고양시 일산동구  26.01.02

[844 rows x 20 columns]

In [57]:
# 거래가 많이 발생한 아파트
result = df["단지명"].value_counts()
display(result.head(10))

단지명
일산요진와이시티      105
일산센트럴아이파크      93
위시티일산자이2단지     66
일산자이더헤리티지      62
강촌마을(라이프)      56
호수마을(현대)       49
하늘마을 5단지       47
위시티블루밍3단지      47
숲속마을8단지        42
위시티일산자이1단지     38
Name: count, dtype: int64

In [58]:
# 전용면적이 84이상이면서 거래금액이 8억 이상인 아파트
area = df["전용면적(㎡)"] >= 84
price = df["거래금액(만원)"] >= 80000
condition = area & price
result = df[condition]
result = result[["단지명","전용면적(㎡)","거래금액(만원)"]]
display(result)

            단지명   전용면적(㎡)  거래금액(만원)
1     킨텍스원시티1블럭   84.4423    135000
23    킨텍스원시티3블럭   84.4423    132500
25     일산요진와이시티   84.3000     85000
33    킨텍스원시티2블럭   84.8127    125000
34     백마마을(삼성)  101.9100     81500
...         ...       ...       ...
1772   일산요진와이시티   84.3000     93500
1783  강촌마을(코오롱)  123.7500     93000
1786  위시티블루밍5단지  154.7400     85000
1787  위시티블루밍5단지  154.7400     85000
1793  킨텍스원시티3블럭   84.5043    128000

[243 rows x 3 columns]

In [66]:
# 아파트별 최고가 최저가 평균가
# result = df.groupby("단지명")["거래금액(만원)"].agg(["max","min","mean","count"])
# result = result.sort_values("mean",ascending=False)
result = df.groupby("단지명")["거래금액(만원)"].agg(최고가 = "max",최저가="min",평균가="mean",거래건수="count")
result = result.sort_values("평균가",ascending=False)
result.to_excel("아파트.xlsx",sheet_name="아파트거래")
display(result)

                 최고가     최저가            평균가  거래건수
단지명
킨텍스원시티2블럭     200000  119000  135409.090909    33
킨텍스원시티3블럭     215000  121000  135303.571429    28
킨텍스원시티1블럭     150000  114000  127580.000000    15
힐스테이트킨텍스레이크뷰  121000   81000   92520.000000    20
일산요진와이시티      157000   46500   90102.857143   105
...              ...     ...            ...   ...
청원네이처빌         25000   17800   20471.428571     7
중산마을2(코오롱)     28000   16900   19801.785714    28
강촌마을(한양6)      22000   16000   19610.000000    20
중산마을1단지(두산)    24000   13400   19198.387097    31
현대그린            8000    6000    7154.545455    11

[104 rows x 4 columns]

In [67]:
# 시트별 개별 저장
price = df["거래금액(만원)"]
result01 =  df[price>=100000]

year = df["건축년도"]
result02 =  df[year < 1995]


result03 = df.groupby("단지명")["거래금액(만원)"].agg(최고가 = "max",최저가="min",평균가="mean",거래건수="count")
result03 = result03.sort_values("평균가",ascending=False)

with pd.ExcelWriter("아파트분석.xlsx",engine="openpyxl") as writer:
    df.to_excel(writer,sheet_name="전체거래", index=False)
    result01.to_excel(writer,sheet_name="10억이상", index=False)
    result02.to_excel(writer,sheet_name="1995년 이전", index=False)
    result03.to_excel(writer,sheet_name="아파트 평균 최고가 최저가", index=False)